### ISSUE TITLE
importing this module is giving error Ng module meta data not found

### ISSUE THREAD

**Issue by codestellar** [tibinthomas/ngx-img-zoom#1]
I am surprised how come its working in demo?

**Comment by codestellar** [comment]
Please reply thank you in advance.

**Comment by codestellar** [comment]
may be its issue with cli . But on hovering lens background positions are not updating too.

**Comment by tibinthomas** [comment]
Thanks for you interest in this. Can you please post your angular environment details. (ng -v ). I will look into it.
