### ISSUE TITLE
No image display in zoom window on first time hover

### ISSUE THREAD

**Issue by VermaMohit230** [tibinthomas/ngx-img-zoom#19]
**On first time hover** no zoom image display 
and when i scroll the mouse scroller than image display

![Untitledd](https://user-images.githubusercontent.com/47655605/73352052-4a860680-42b6-11ea-9828-a218a78779f0.png)

**Comment by tibinthomas** [comment]
A possible reason for this can be an incorrect usage of the input properties.

**Comment by tibinthomas** [comment]
A possible reason for this can be an incorrect usage of the input properties.

How it internally works is, if the preview URL image is loaded it will use that image for zooming too and asynchronously loads the high-quality zoom image, once this high-quality image is completely loaded preview image that was beeing using as zoom image will be replaced with the high-quality image.

Please keep this in mind and try solving the issue. If you are still facing issue plz create a stackblitz demo with minimal reproducible code.

Thank you.
