### ISSUE TITLE
Cannot read property 'parentElement' of undefined

### ISSUE THREAD

**Issue by lynx-r** [tibinthomas/ngx-img-zoom#4]
I got an error with this code 

https://stackblitz.com/edit/angular-f7av9x

I think the problem appears while binding property `lensStyle`, the method 

https://github.com/tibinthomas/ngx-img-zoom/blob/f9b3fda4a891a658d7c42606d3318e9d775e8103/projects/ngx-img-zoom/src/lib/ngx-img-zoom.component.ts#L45

is called. But it doesn't have an instance of `this.img`

https://github.com/tibinthomas/ngx-img-zoom/blob/f9b3fda4a891a658d7c42606d3318e9d775e8103/projects/ngx-img-zoom/src/lib/ngx-img-zoom.component.ts#L110

which is initialised only there:

https://github.com/tibinthomas/ngx-img-zoom/blob/f9b3fda4a891a658d7c42606d3318e9d775e8103/projects/ngx-img-zoom/src/lib/ngx-img-zoom.component.ts#L87

**Comment by tibinthomas** [comment]
Thanks for your time and interest in this package.

I would suggest you to use ver 3.3.1 until I find a fix for this issue.

Thanks again.

**Comment by tibinthomas** [comment]
This issue is fixed in ver 3.4.0.

**Comment by tvcong0999** [comment]
I am using version 4.1.2 and it also has this bug

**Comment by Piratelord17** [comment]
Any updates in this issue?

**Comment by SantiagoAlv97** [comment]
Hi, any updates in this issue?
