### ISSUE TITLE
zoom in  zoom out  functionality

### ISSUE THREAD

**Issue by sanketmunjq** [tibinthomas/ngx-img-zoom#6]
can you please add zoom in-  zoom out  functionality.

**Comment by tibinthomas** [comment]
Thanks for your heed in this library.

Can you please elaborate this functionality?
Do you have any design in find to achieve this? If possible share a design and I will consider this in the next update.

Thanks again

**Comment by sanketmunjq** [comment]
on mouse scroll 'img-zoom-lens' height and width should be increase or decreases . and imageZoom function  should be call after it.

**Comment by tibinthomas** [comment]
Okay. Thanks got it.

**Comment by tibinthomas** [comment]
This functionality is available from 4.0.0.
Thanks...

**Comment by sanketmunjq** [comment]
![ngx-img-zoom_error](https://user-images.githubusercontent.com/54016892/63586397-d8025380-c5be-11e9-96e9-744faf741510.PNG)
can you please help me?

**Comment by tibinthomas** [comment]
Documentation for using zoom is on the way.
Thanks for being on of the beta testers of this version. 
For now you can refer the sample project to implement the zoom functionality. 

https://github.com/tibinthomas/ngx-img-zoom/blob/master/src/app/app.component.ts

**Comment by sanketmunjq** [comment]
thank you . currently error is solved but image zoom function not smoothly  some time.its lagging (no error )
